import React from "react";

export default function TermsPage() {
    return (
    <main className="max-w-3xl mx-auto p-6 text-gray-800">
        <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
        <h2 className="text-3xl mb-6">Terms & Conditions regarding use of investment advisory services and StockAmplify</h2>

        <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Overview</h2>
        <p>
            This website is operated by StockAmplify. Throughout the site, the terms “we”, “us” and “our” refer to StockAmplify who offers this website, and all other information, tools, utilities and services available from this site to you, the user, subject to you accepting and agreeing to be bound by these terms and conditions.
            StockAmplify is an Artificial Intelligence based stock educator website, which helps user to analyse stock. User (investor) should do its own analysis and contact advisor before taking investment decisions based on StockAmplify stock analysis and information decision.
            By visiting our site, you agree to be bound by the following terms and conditions (“Terms of Service” or “Terms”), including those additional terms and conditions and policies referenced herein and/or available by following hyperlink, or as may be updated from time to time. These Terms of Service apply to all users of the site and/or the Product, including without limitation users who are browsers, vendors, clients, merchants, and/or contributors of content.
            Please read these Terms of Service carefully before accessing or using our website, agreeing to subscribe to the Product, using our mobile application or using the Product. If you do not agree to all the Terms, then you may not access the website or use any Services. If these Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service. By accepting these Terms, electronically, (for example by clicking “Submit” or “I Agree”), accessing or using the Services or the Product, you agree to these terms.
            The Agreement (as defined below) is an electronic record in terms of the Information Technology Act, 2000, generated by a computer system and does not require any physical or digital signature.
            Any new features or tools which are added to the current site, mobile application or the Product shall also be subject to these Terms. You can review the most current version of these Terms at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website, mobile application and/ or the Product, following the posting of any changes constitutes acceptance of those changes.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">DEFINITIONS AND INTERPRETATION</h2>
        <p>
            DEFINITIONS
            In these Terms, unless otherwise defined, the following terms shall have the meaning as follows:
            •	Agreement means the agreement between the Client and StockAmplify arising from the Client accepting these Terms.
            •	Broker refers to any third-party broker who provides stock broking services to the Client.
            •	Loss or Losses means any direct, indirect, incidental, special, consequential or exemplary losses, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible Losses (even if StockAmplify has been advised of the possibility of such Losses), claims, penalties, damages, liabilities (including legal and other costs and expenses reasonably incurred while investigating or defending against such loss, claim, damages or liabilities). Losses also include any duties, levies, taxes and cess payable on the Loss;
            •	Regulations shall mean the Securities and Exchange Board of India (Investment Advisers Regulations) 2013, as in force from time to time;
            •	Securities shall have the meaning given to it in Section 2(h) of Securities Contract (Regulation) Act, 1956.
            •	Services means the services set out in paragraph 4 below.
            •	SEBI means the Securities and Exchange Board of India.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Intellectual Property</h2>
        <p>
          All content, trademarks, and data on this website are the property of
          StockAmplify or its licensors and are protected by copyright and other
          intellectual property laws.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">      
        <section className="mb-4">
            <h2 className="text-xl font-semibold mb-2">RIGHTS OF StockAmplify</h2>
            <p>
                StockAmplify reserves the right to de-register any user for any reason at any time.
                StockAmplify can grant differential access with different rights to different Users.
            </p>
      </section>
    </section>

       <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Modification / Alteration of Terms and Conditions</h2>
        <p>
            StockAmplify reserves the right to modify the Terms and Conditions any time in future and the revised terms shall automatically be updated and can be accessed through the web link provided on webpage accessible to you. Your continued use of StockAmplify following changes to this section will mean that you accept changes to these terms. If you do not agree to the modification, you must discontinue using the services.
            We reserve the right to discontinue or alter any or all of our website services, and to stop publishing our website, at any time in our sole discretion without notice or explanation; and save to the extent expressly provided otherwise in these terms and conditions, you will not be entitled to any compensation or other payment upon the discontinuance or alteration of any website services, or if we stop publishing the website.
        </p>
      </section>

      <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">INTERPRETATION</h2>
        <p>
            All references in these Terms to any statute or any statutory provisions shall be construed as meaning and including references to:
            •	any modification, consolidation or re-enactment of the statute in force from time to time;
            •	all delegated legislation made pursuant to a statutory provision; and
            •	any statutory provisions of which these statutory provisions are a consolidation, re-enactment or modification.
            References to paragraphs shall be to paragraphs of these Terms.
            All titles, subject headings, table of contents and similar items are provided for the purpose of reference and convenience and are not intended to affect the meaning of the content or scope of these Terms.
            The words 'including', 'include' and 'in particular' shall be construed as being by way of illustration only and shall not be construed as limiting the generality of the preceding words.
            References to the singular number shall include references to the plural number and vice versa.
            If any word or phrase is defined, its other grammatical forms or conjugations shall have a corresponding meaning.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">THE StockAmplify Website (The Product):</h2>
        <p>
            The Client understands that the StockAmplify is an Artificial Intelligence based strategy, which allows users (investors) to analyse equity stocks, while factoring in the investor's investment horizon but it does not make any investment or trading decisions, both of which must be made by the Client. If the Client wishes to use the StockAmplify, the Client must open an online account on the Site.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">SCOPE OF SERVICES</h2>
        <p>
            During the Term, and subject to the Client making payment of the fees prescribed by StockAmplify, StockAmplify shall provide access to website services, on a non-exclusive basis, entirely at the Client's risk (the “Services”).
            StockAmplify does not provide broking services. Any investment or trading decisions must be made by the Client.
            The Client may enter into a separate agreement with a Broker for stock broking services. All such services are governed by that agreement and are outside the scope of StockAmplify.
            The Client retains full discretion to:
            Choose whether to act upon the analysis and insights provided by StockAmplify.
            Choose their preferred Broker for executing trades.
            The Investment Advisor shall have no authority or obligation to enforce or ensure the Client acts upon any advice.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">RESPONSIBILITIES OF THE CLIENT</h2>
        <p>
            The Client understands and acknowledges that the Portfolio is created based on the information provided by the Client and the Investment Advisor shall not be liable to the Client, for any Loss arising to the Client as a result of or in connection with the Client providing inaccurate information to the Investment Advisor.
            The advice and recommendations given to the Client are intended strictly for the Client’s benefit, and no other persons shall be entitled to rely on such information.
            The Client is responsible for maintaining the confidentiality of its account and password and for restricting access to its computer to prevent unauthorized access to its account. The Client hereby agrees to accept responsibility for all activities that occur under its account or password.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">TERM</h2>
        <p>
            This Agreement shall commence on the date on which the Client subscribes to the Product (hereinafter referred to as the “Commencement Date”) and shall remain valid until terminated in accordance with these Terms (“Term”).
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">FEES</h2>
        <p>
            The client agrees to pay a consideration for the services provided herein in the manner listed below.
            StockAmplify reserves the right to revise the Fees (or any component thereof) from time to time.
            In the event that the Client fails to make payment of the Fees or any part thereof, within Five (5) days from the date when the Fee(s) became due, then without prejudice to any other rights or remedies of StockAmplify under this Agreement or at law, StockAmplify may suspend providing the Services and disable the access of the Client to the website.
            StockAmplify has provided a payment gateway platform for your convenience and does not take any direct or indirect, explicit or implicit responsibility for any complaint or dispute arising out of such payment made on such payment gateway for any reasons whatsoever. The Fees must be paid by the Client directly to StockAmplify by electronic funds transfer, cheque or demand draft.
        </p>
      </section>

    <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">REFUND & CANCELLATION POLICY</h2>
        <p>
            A client/subscriber paying the fees on monthly basis can cancel the subscription only after the completion of 30 days. The Company does not owe any liability to refund the monthly subscription charges should the subscriber decide to discontinue availing services or terminates the account or under any other circumstances whatsoever. Subscription charges paid for a month shall not be refunded.
            A client/subscriber paying the fees on yearly basis can cancel the subscription by giving 3 months advance notice. The subscription shall be cancelled on the expiry of 3 months. The subscriber shall be entitled to get a refund of the unexpired period of subscription after deducting 3 months' subscription fees. StockAmplify shall deduct 3 months' subscription as termination charges.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">CONFIDENTIALITY</h2>
        <p>
            StockAmplify shall treat all personal information provided by the Client with the utmost care and shall use the personal information for providing the Services to the Client. The Client agrees that StockAmplify may contact the Client either through calls, messages or otherwise on their phone number (landline or mobile) in connection with the Services to be provided by StockAmplify, and any such communications from StockAmplify shall not be treated as unsolicited communications.
            Notwithstanding the foregoing, StockAmplify may disclose the personal information of the Client to:
            •	(a) the Broker, its agents, custodians, service providers engaged by StockAmplify to assist it in providing the Services and for marketing purposes;
            •	(b) if required by an appropriate government authority or by the Regulations, provided that where permissible under applicable law, StockAmplify shall provide appropriate notice to the Client before making such disclosure.
            StockAmplify shall also be entitled to use the Client's name in any client list or in relation to sales, marketing, and reference purposes.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">RISKS</h2>
        <p>
            Any investment or trading decisions are made by the Client entirely at their own risk and cost. The Client expressly acknowledges and agrees that all investments in Securities are subject to market risks and there cannot be any assurance or guarantee that the objective of investments will be achieved, or that the returns shall always be accretive. The past performance of the Product does not indicate or guarantee its future performance.
            The analysis given by StockAmplify may not always result in a correct analysis for the Client, as market movements may be at variance with anticipated trends.
            Any changes in the trading regulations by the recognized stock exchange(s) or SEBI may prevent the investment in Securities from achieving stated objectives.
            StockAmplify shall not be held responsible for losses based on the analysis provided.
            Except as may otherwise be provided by law, StockAmplify will not be liable to the Client for:
            •	(a) any Loss that the Client may suffer by reason of any investment decision made or other action taken with any investment in Securities.
            StockAmplify has launched the Product on 20th Sept 2025, and thus neither StockAmplify nor the Product has any track record with regard to the Services.
            The Client agrees that the investments have been or will be made by the Client on their own volition and not under coercion or on the basis of promises of returns or any other guarantee whatsoever. StockAmplify shall not be liable for any loss on account of any investment decision taken by the Client. Moreover, StockAmplify does not guarantee 100% accuracy of any data or analysis offered to its users.
            The Client shall be responsible for reviewing any warnings or disclaimers in offering documents, advertising materials, or any other documents or information issued by an issuer of Securities before making any investment decisions.
        </p>
      </section>

    <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">LIABILITY OF STOCKAMPLIFY</h2>
        <p>
            The parties hereby agree that any and all risks and losses incurred or suffered by the Client in pursuance of investment advice rendered by StockAmplify shall be borne solely and exclusively by the Client.
            The Client expressly understands and agrees that StockAmplify shall not be liable to the Client for any losses resulting from:
            •	making investments or trading decisions based on the stock analysis provided by StockAmplify, the use or the inability to use the Services and/or the Product;
            •	unauthorized access to or alteration of the Client's transmissions or data;
            •	failure of the Client to comply with applicable law;
            •	any other matter relating to the Services and/or the Products.
            If StockAmplify is held liable for any losses, its maximum liability shall be limited to the subscription amount paid by the Client to StockAmplify for the relevant period of subscription.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">CONFLICT OF INTERESTS</h2>
        <p>
            StockAmplify is not obligated to buy, sell, or recommend any security or other investment to the Client.
        </p>
      </section>

                <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">REPRESENTATIONS, WARRANTIES AND DECLARATIONS</h2>
        <p>
            The Client hereby represents, warrants, declares, and undertakes to the Investment Advisor as under:
            •	The Client has full legal capacity and authorizations to enter into this Agreement and upon the Client accepting these Terms, this Agreement shall form a legal, valid, and binding obligation on the Client, enforceable against the Client in accordance with its terms.
            •	The execution, delivery, and performance by the Client of this Agreement and the acts and transactions contemplated hereby do not and will not, with or without the giving of notice or lapse of time or both, violate, conflict with, require any consent under or result in a breach of or default under:
            o	(a) any law (including the Regulations) to which they are subject;
            o	(b) any order, judgment, or decree applicable to them;
            o	(c) any term, condition, covenant, undertaking, agreement, or other instrument to which they are a party or by which they are bound.
            •	The Client has read this Agreement and is aware of all the risks associated with the nature of the Services and the transactions contemplated under this Agreement, whether set out in the Agreement or not, and shall not hold the Investment Advisor and/or any person appointed by it, responsible for the same.
        </p>
      </section>

                <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">GOVERNING LAW AND JURISDICTION</h2>
        <p>
            These Terms and the Agreement shall be governed by the laws of India. Subject to paragraph 18 below, the courts of Maharashtra shall have exclusive jurisdiction in respect of any dispute arising out of or in connection with this Agreement.
        </p>
      </section>

                <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">GRIEVANCE REDRESSAL AND DISPUTE RESOLUTION</h2>
        <p>
            The Client should promptly notify any grievances to the Investment Advisor in writing, giving sufficient details to enable the Investment Advisor to take necessary steps.
            On receipt of any grievances, StockAmplify shall take prompt action to redress the same. If the grievance persists, all claims and disputes arising out of or in connection with this Agreement or its performance or any non-contractual claims arising between the parties shall be settled by arbitration by a sole arbitrator mutually acceptable to the parties. If the parties fail to agree on the appointment of a sole arbitrator within 30 days of the dispute being referred to arbitration, the sole arbitrator shall be appointed in accordance with the Arbitration & Conciliation Act, 1996 (as amended).
            The arbitration shall be governed by the provisions of the Arbitration & Conciliation Act, 1996 (as amended) and unless otherwise agreed by the parties, arbitration proceedings shall be held in Maharashtra in the English language.
        </p>
      </section>

          <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">MISCELLANEOUS</h2>
        <p>
            This Agreement represents the complete agreement of the parties with regard to the subject matter and supersedes any prior understanding or agreements, oral or written.
            No provision hereof or breach of any provision may be waived except by a written waiver, signed by the waiving Party. No waiver of any right under or breach of this Agreement shall be construed to be a waiver of any other right or breach.
            If any provision of this Agreement or the application thereof to any person or circumstance shall be invalid or unenforceable to any extent, the remainder of this Agreement and the application of such provision to persons or circumstances other than those as to which it is held invalid or unenforceable shall not be affected thereby, and each provision of this Agreement shall be valid and enforceable to the fullest extent permitted by the applicable law. Any invalid or unenforceable provision of this Agreement shall be replaced with a provision which is valid and enforceable and most nearly reflects the original intent of the unenforceable provision.
            The Investment Advisor shall have the full liberty and absolute discretion to make necessary changes in the Agreement and/or do any act, deed, matter or thing necessary to comply with any law for the time being in force, and the Investment Advisor shall not be held liable for the same. Further, the Investment Advisor reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Services and/or the Product (or any part thereof) with or without notice. The Client agrees that StockAmplify shall not be liable to the Client or to any third party for any modification, suspension or discontinuance of the Services and/or the Product during the subscription period. Except for the above, no amendment or modification of this Agreement and no waiver of any of these Terms shall be valid or binding unless mutually agreed by the parties.
            None of the provisions of this Agreement shall be deemed to constitute a partnership between the parties, and no party shall have any authority to bind the other party otherwise than as contemplated under this Agreement.
        </p>
      </section>

    <section className="mb-4">
        <h2 className="text-xl font-semibold mb-2">Notices</h2>
        <p>
            Any notice, demand or other communication to be made under or in connection with this Agreement shall be made in writing unless otherwise stated. Such notice, demand, request or other communication shall be deemed to have been duly given or made when it shall be (i) delivered personally; or (ii) sent by facsimile; or (iii) sent by registered mail with acknowledgment due, postage prepaid or courier; or (iv) sent by email (provided that the email is followed up with a copy by any of the aforesaid modes) to – in the case of StockAmplify, at its registered office address, and in the case of the Client, to the last address provided by the Client to StockAmplify. A party may change their address with written intimation to the other party.
            Any questions about these Terms should be sent to us at stocka  mplifyfeedback@gmail.com.
        </p>
      </section>
    </main >
  );
}